name: animated_stream_list_nullsafety
description: A Flutter library to easily display a list with animated changes
  from a Stream<List<E>>. It's like StreamBuilder + ListView.Builder with
  animations.
version: 2.0.3
homepage: https://github.com/hig-dev/animated-stream-list

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  mockito: ^5.0.0
  quiver: ^3.0.0

flutter: null